version: '3.8'

services:
  bstackdb:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: bstack_db
      MYSQL_USER: bstack_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  bstackadminer:
    image: adminer
    restart: always
    depends_on:
      - bstackdb
    ports:
      - 8081:8080
